libldb: allow python pkg to be excluded
There are conflicts with the samba python package
so disable the python pkg by default to fix:

The pyldb has an RDEPENDS on samba which is causing issues with other
packages.

ERROR: The file /usr/lib/python2.7/site-packages/_ldb_text.py is installed by both libldb and samba, aborting

Also cleanup per style guide

Signed-off-by: Armin Kuster <akuster808@gmail.com>
Signed-off-by: Khem Raj <raj.khem@gmail.com>